using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraControl : MonoBehaviour
{
    [SerializeField] PlayerController m_target; //’اگص‘خڈغ‚جƒIƒuƒWƒFƒNƒg.
    [SerializeField] private Vector3 offset; //’اگص‘خڈغ‚©‚ç‚ج‹——£.
    private bool m_canChasing; //’اگصƒtƒ‰ƒO.

    //’اگص’†ژ~.
    public void StopChase()
    {
        m_canChasing = false;
    }

    // Update is called once per frame
    void Update()
    {
        //–ع•W‚©‚çˆê’è‹——£—£‚µ‚ؤ’اگص.
        if (m_canChasing == true)
        {
            transform.position = m_target.transform.position + new Vector3(offset.x, offset.y, offset.z);
        }
    }
}
